export type ProjectCategory = "Réseaux sociaux" | "Print";
export type Project = {
  id: string;
  category: ProjectCategory;
  title: string;
  description: string;
  src: string;
  pdf?: string;
};

export const projects: Project[] = [
  {
    id: "soc-horaires",
    category: "Réseaux sociaux",
    title: "14 juillet : Horaires Intermarché",
    description: "Création d'un visuel annonçant les horaires exceptionnels des magasins Intermarché Mainvilliers et Chartres Les 3 Ponts à l'occasion de la fête nationale, diffusé sur les réseaux sociaux.",
    src: "/images/projects/social/horaires.png",
  },
  {
    id: "soc-delices",
    category: "Réseaux sociaux",
    title: "Délices & Planches",
    description: "Visuel mettant en valeur l'offre de planches apéritives Délices & Planches, réalisé dans le respect de la charte graphique.",
    src: "/images/projects/social/delices-planches.png",
  },
  {
    id: "soc-ecoupon",
    category: "Réseaux sociaux",
    title: "E-coupon de la semaine",
    description: "Visuel promotionnel conçu pour relayer le e-coupon hebdomadaire disponible sur l'application Intermarché.",
    src: "/images/projects/social/e-coupon.png",
  },
  {
    id: "soc-saviez",
    category: "Réseaux sociaux",
    title: "Le saviez-vous ? Conservation des tomates",
    description: "Visuel au format « Le saviez-vous ? », destiné à informer et fidéliser la communauté Intermarché sur les réseaux sociaux.",
    src: "/images/projects/social/le-saviez-vous.png",
  },
  {
    id: "soc-plateau",
    category: "Réseaux sociaux",
    title: "Plateaux de fruits de mer",
    description: "Visuel valorisant l’offre de plateaux de fruits de mer, pensé pour faire découvrir ce rayon aux clients via les réseaux sociaux.",
    src: "/images/projects/social/plateau-fruits-de-mer.png",
  },
  {
    id: "soc-publication",
    category: "Réseaux sociaux",
    title: "Pâtisseries Délices & Planches",
    description: "Publication mettant en avant les pâtisseries proposées par Délices & Planches, en renvoyant vers le site internet dédié.",
    src: "/images/projects/social/publication-dp.png",
  },
  {
    id: "soc-promotions",
    category: "Réseaux sociaux",
    title: "Réel promotion",
    description: "Réel diffusé sur les réseaux sociaux d’Intermarché pour présenter les promotions de la semaine de façon dynamique.",
    src: "/images/projects/social/promotions.mp4",
  },
  {
    id: "soc-noel",
    category: "Réseaux sociaux",
    title: "Réel Noël",
    description: "Réel de fin d’année mettant en avant les menus festifs, bûches et bûchettes, ainsi que le site Délices & Planches et son offre de -10 %.",
    src: "/images/projects/social/reel-noel.mp4",
  },
  {
    id: "soc-resolutions",
    category: "Réseaux sociaux",
    title: "Réel résolution Noël",
    description: "Réel au ton humoristique, valorisant le rayon fruits & légumes ainsi que le rayon épicerie et ses gâteaux, dans une approche « bonnes résolutions ».",
    src: "/images/projects/social/resolutions.mp4",
  },
  {
    id: "soc-appareil-photo",
    category: "Réseaux sociaux",
    title: "Journée nationale de l’appareil photo",
    description: "Visuel d’engagement pour le 29 juin : argentique ou numérique, une question posée en feed avec les deux appareils mis en scène.",
    src: "/images/projects/social/journee-appareil-photo.png",
  },
  {
    id: "soc-saviez-photo",
    category: "Réseaux sociaux",
    title: "Le saviez-vous ? — l’appareil photo numérique",
    description: "Infographie Intermarché sur l’invention du premier appareil photo numérique en 1975, dans la série « Le saviez-vous ? ».",
    src: "/images/projects/social/saviez-vous-photo.png",
  },
  {
    id: "soc-buches",
    category: "Réseaux sociaux",
    title: "Commandez depuis chez vous — bûches",
    description: "Visuel Délices & Planches pour les fêtes : commande en ligne, −10 % sur les bûches, et QR code vers le site.",
    src: "/images/projects/social/commande-buches.png",
  },
  {
    id: "soc-eau-drive",
    category: "Réseaux sociaux",
    title: "Bouteille d’eau offerte au drive",
    description: "Opération canicule : une bouteille d’eau offerte pour toute commande drive passée le lundi, posée sur une photo du drive.",
    src: "/images/projects/social/bouteille-eau-drive.png",
  },
  {
    id: "soc-jambon",
    category: "Réseaux sociaux",
    title: "Jambon sec noir de Bigorre",
    description: "Mise en avant produit : comment déguster le jambon sec noir de Bigorre, du pain de campagne au verre de vin.",
    src: "/images/projects/social/jambon-noir-de-bigorre.png",
  },
  {
    id: "soc-mots-caches",
    category: "Réseaux sociaux",
    title: "Mots cachés — été",
    description: "Jeu de mots cachés estival pour le feed, grille lisible sur fond de toile de transat.",
    src: "/images/projects/social/mots-caches.png",
  },
  {
    id: "soc-tour-magasin",
    category: "Réseaux sociaux",
    title: "Reel — tour du magasin",
    description: "Court format vertical dans les allées : ambiance magasin et mise en avant de produits du quotidien.",
    src: "/images/projects/social/tour-magasin.mp4",
  },
  {
    id: "soc-recette",
    category: "Réseaux sociaux",
    title: "Reel — devinez la recette",
    description: "Reel participatif : les ingrédients défilent pour faire deviner la recette, avec le texte à l’écran.",
    src: "/images/projects/social/devinez-la-recette.mp4",
  },
  {
    id: "soc-courses-pq",
    category: "Réseaux sociaux",
    title: "Reel — courses et papier toilette",
    description: "Sketch en magasin qui se termine sur le rayon papier toilette, monté pour le format vertical.",
    src: "/images/projects/social/courses-pq.mp4",
  },
  {
    id: "soc-pq",
    category: "Réseaux sociaux",
    title: "Reel — PQ",
    description: "Parcours de courses en magasin, du rayon biscuits jusqu’à la carte de fin Intermarché.",
    src: "/images/projects/social/pq.mp4",
  },
  {
    id: "soc-chips-coca",
    category: "Réseaux sociaux",
    title: "Reel — chips ou Coca-Cola ?",
    description: "Dilemme à l’écran, chips barbecue ou Coca-Cola, pensé pour l’interaction en commentaires.",
    src: "/images/projects/social/chips-ou-coca.mp4",
  },
  {
    id: "soc-cinq-produits",
    category: "Réseaux sociaux",
    title: "Reel — 5 produits de la semaine",
    description: "Sélection de la semaine en rayon : fruits, fromages et gourmandises, au rythme d’un reel vertical.",
    src: "/images/projects/social/cinq-produits-semaine.mp4",
  },
  {
    id: "soc-astuce-frais",
    category: "Réseaux sociaux",
    title: "Réel astuce frais",
    description: "Réel humoristique mettant en scène des produits frais, pensé pour accompagner les clients pendant la canicule.",
    src: "/images/projects/social/astuce-frais.mp4",
  },
  {
    id: "soc-jouet",
    category: "Réseaux sociaux",
    title: "Reel — implantation jouets",
    description: "Balayage du rayon jouets : mise en rayon et lisibilité de l’offre en format vertical.",
    src: "/images/projects/social/implantation-jouet.mp4",
  },
  {
    id: "soc-petit-dej",
    category: "Réseaux sociaux",
    title: "Reel — petit-déjeuner",
    description: "Tour du petit-déjeuner, de la viennoiserie aux œufs, filmé pour le feed.",
    src: "/images/projects/social/petit-dej.mp4",
  },
  {
    id: "soc-pov-regime",
    category: "Réseaux sociaux",
    title: "Réel régime",
    description: "Réel humoristique jouant sur le thème classique du « régime qui ne tient jamais » avant les fêtes.",
    src: "/images/projects/social/pov-regime.mp4",
  },
  {
    id: "soc-moins-2",
    category: "Réseaux sociaux",
    title: "Reel — produits à moins de 2 €",
    description: "Recherche façon moteur puis rayon : les produits à moins de 2 €, avec les pastilles « C’est contre la vie chère ».",
    src: "/images/projects/social/produits-moins-2-euros.mp4",
  },
  {
    id: "soc-boucherie",
    category: "Réseaux sociaux",
    title: "Reel — rayon boucherie",
    description: "Mise en avant du rayon boucherie, brochettes et prix, avec le titre posé à l’écran.",
    src: "/images/projects/social/rayon-boucherie.mp4",
  },
  {
    id: "soc-24-07",
    category: "Réseaux sociaux",
    title: "Reel du 24 juillet",
    description: "Tour des rayons traiteur et charcuterie, habillé du cartouche Intermarché Mainvilliers et Chartres Les 3 Ponts.",
    src: "/images/projects/social/reel-24-07.mp4",
  },
  {
    id: "soc-wrap",
    category: "Réseaux sociaux",
    title: "Reel — wrap saumon fumé",
    description: "Les courses d’une recette de wrap au saumon fumé : tortillas, frais et épicerie, en enchaînement vertical.",
    src: "/images/projects/social/wrap-saumon-fume.mp4",
  },
  {
    id: "prt-voeux",
    category: "Print",
    title: "Carte de vœux de fin d’année – Sparkling Communication",
    description: "Réalisée lors de mon stage chez Sparkling Communication, cette carte de vœux respecte l’identité visuelle de l’agence.",
    src: "/images/projects/print/previews/bonne-annee.png",
    pdf: "/images/projects/print/bonne-annee.pdf",
  },
  {
    id: "prt-maryland",
    category: "Print",
    title: "Menu de Noël – Le Maryland à Lèves",
    description: "Conception d’un menu de Noël pour le Maryland dans le cadre de mon stage chez Sparkling Communication, destiné à être affiché dans le bar de l’établissement.",
    src: "/images/projects/print/previews/affiche-maryland.png",
    pdf: "/images/projects/print/affiche-maryland.pdf",
  },
  {
    id: "prt-newsletter",
    category: "Print",
    title: "Newsletter – Août 2026",
    description: "Newsletter interne conçue dans le cadre de mon alternance, publiée tous les mois. J’y assurais la mise à jour des anniversaires des collaborateurs, l’arrivée des nouveaux entrants et les actualités du magasin.",
    src: "/images/projects/print/previews/newsletter-aout-2026.png",
    pdf: "/images/projects/print/newsletter-aout-2026.pdf",
  },
  {
    id: "prt-olac",
    category: "Print",
    title: "Dépliant – O’Lac Guinguette de Luisant",
    description: "Création d’un dépliant présentant les services proposés par la guinguette de Luisant, réalisée lors de mon stage.",
    src: "/images/projects/print/previews/proposition.png",
    pdf: "/images/projects/print/proposition.pdf",
  },
  {
    id: "prt-flyer",
    category: "Print",
    title: "Flyer Délices & Planches",
    description: "Flyer conçu durant mon alternance pour mettre en avant les produits Délices & Planches, incluant un QR code ainsi que les coordonnées et adresses des magasins Intermarché Mainvilliers et Chartres Les 3 Ponts.",
    src: "/images/projects/print/previews/flyer-delices-planches.png",
    pdf: "/images/projects/print/flyer-delices-planches.pdf",
  },
  {
    id: "prt-drive",
    category: "Print",
    title: "Flyers code promo – Drive",
    description: "Création de flyers destinés au service Drive pour promouvoir le code promo du mois, glissés directement dans les commandes clients afin d’encourager leur utilisation.",
    src: "/images/projects/print/previews/code-promo-drive.png",
    pdf: "/images/projects/print/code-promo-drive.pdf",
  },
  {
    id: "prt-publireportage",
    category: "Print",
    title: "Publireportage – Lancôme",
    description: "Réalisé dans le cadre de mon BTS Communication, ce publireportage met en avant La Nuit Trésor, un best-seller de la marque Lancôme.",
    src: "/images/projects/print/publireportage.jpg",
  },
  {
    id: "prt-sparkling",
    category: "Print",
    title: "Flyer – Sparkling Communication",
    description: "Flyer présentant les services proposés par l’agence, créé lors de mon stage chez Sparkling Communication.",
    src: "/images/projects/print/previews/document-1.png",
    pdf: "/images/projects/print/document-1.pdf",
  },
];
